version: '1.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silver_real_estate_backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
